###
GET http://localhost:8080/api/players
Accept: application/json


###
GET http://localhost:8080/api/players/1
Accept: application/json

###
POST http://localhost:8080/api/players
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "phoneNumber": "+1234567890",
  "email": "john.doe@example.com",
  "gender": "Male",
  "ratingCode": "3.5",
  "location": "Atkinson",
  "availability": ""
}

